# Generated by Django 3.0.7 on 2021-03-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazstaviVieta',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.Problem')),
                ('minimalna_vrednost', models.SmallIntegerField(default=-9)),
                ('maksimalna_vrednost', models.SmallIntegerField(default=9)),
                ('minimalen_vodilni_koeficient', models.SmallIntegerField(default=1)),
                ('maksimalen_vodilni_koeficient', models.SmallIntegerField(default=1)),
            ],
            bases=('problems.problem',),
        ),
    ]
